---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: install
  image: danlynn/ember-cli:3.28.2
  commands:
  - npm ci
- name: lint
  image: danlynn/ember-cli:3.28.2
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:3.28.2
  commands:
  - npm run test:ember
- name: precompile
  image: danlynn/ember-cli:3.28.2
  commands:
  - ember ts:precompile
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: verify-build
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/ember-rdfa-editor
    dry_run: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/ember-rdfa-editor
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - development
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: ember-compat-test
steps:
- name: ember-try
  image: danlynn/ember-cli:3.28.2
  commands:
    - npm ci
    - npm run test:ember-compatibility
  failure: ignore
trigger:
  branch:
    - development
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: install dependencies
  image: danlynn/ember-cli:3.28.2
  commands:
    - npm ci
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/ember-rdfa-editor
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: qxhPonu4ydzxuOAN8PgespnNNp5dpuep/IqVXjHSBGbUPmouw7Eh6Q==
---
kind: secret
name: docker_password
data: rUpRXFXYZ+wyFlshEl8T0SrUEhCyO4TmjSSgxUhANv4CcfdA3SjT2B5ndVTw8zBeDaNlJ4XJBuyY65gRssr5EQ==
---
kind: secret
name: npm_access_token
data: GrKv0avLg7OMiirYoRceI3ktIBjZeFYt2yblNKuAxUY46SBgX8yPtCe82q5ASQY2kfEwT+FDB1MkpTJDXU0z8nZDzrM=
---
kind: signature
hmac: a506def5e16463b6ae930259bbb866633ae7f7f104e7a1ac5c7c0d0467164d3f

...
