---
kind: pipeline
type: docker
name: default
steps:
- name: test
  image: madnificent/ember:3.20.0
  commands:
  - npm install
  - npm test
- name: build
  image: plugins/docker
  settings:
    repo: lblod/ember_rdfa_editor
    user:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dry_run: true
    purge: true
