---
kind: pipeline
type: docker
name: default
steps:
- name: npm install
  image: madnificent/ember:3.20.0
  commands:
  - npm install
  - npm test
  when:
    ref:
      - refs/pull/*/
      - refs/heads/development
