---
kind: pipeline
type: docker
name: default
steps:
- name: dockerize
  image: docker
  commands:
  - docker build . -t ember-rdfa-editor:${DRONE_BUILD_NUMBER} -t ember-rdfa-editor:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
- name: lint
  image: "ember-rdfa-editor:${DRONE_BUILD_NUMBER}"
  commands:
    - npm run lint
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
