/* eslint-disable @typescript-eslint/no-explicit-any */
import type {
  Transaction,
  EditorState,
  Plugin,
  Command,
} from 'prosemirror-state';
import * as pmh from 'prosemirror-history';

/**
Set a flag on the given transaction that will prevent further steps
from being appended to an existing history event (so that they
require a separate undo command to undo).
*/
const closeHistory: (tr: Transaction) => Transaction = pmh.closeHistory;
interface HistoryOptions {
  /**
    The amount of history events that are collected before the
    oldest events are discarded. Defaults to 100.
    */
  depth?: number;
  /**
    The delay between changes after which a new group should be
    started. Defaults to 500 (milliseconds). Note that when changes
    aren't adjacent, a new group is always started.
    */
  newGroupDelay?: number;
}
/**
Returns a plugin that enables the undo history for an editor. The
plugin will track undo and redo stacks, which can be used with the
[`undo`](https://prosemirror.net/docs/ref/#history.undo) and [`redo`](https://prosemirror.net/docs/ref/#history.redo) commands.

You can set an `"addToHistory"` [metadata
property](https://prosemirror.net/docs/ref/#state.Transaction.setMeta) of `false` on a transaction
to prevent it from being rolled back by undo.
*/
const history: (config?: HistoryOptions) => Plugin = pmh.history;
/**
A command function that undoes the last change, if any.
*/
const undo: Command = pmh.undo;
/**
A command function that redoes the last undone change, if any.
*/
const redo: Command = pmh.redo;
/**
A command function that undoes the last change. Don't scroll the
selection into view.
*/
const undoNoScroll: Command = pmh.undoNoScroll;
/**
A command function that redoes the last undone change. Don't
scroll the selection into view.
*/
const redoNoScroll: Command = pmh.redoNoScroll;
/**
The amount of undoable events available in a given state.
*/
const undoDepth: (state: EditorState) => any = pmh.undoDepth;
/**
The amount of redoable events available in a given editor state.
*/
const redoDepth: (state: EditorState) => any = pmh.redoDepth;
/**
Returns true if the given transaction was generated by the history
plugin.
*/
const isHistoryTransaction: (tr: Transaction) => boolean =
  pmh.isHistoryTransaction;
/**
Returns the unique ID of the current history for a given editor state.
This can for example be used to compare against a saved state, to
determine if there are changes since then.
*/
const getHistoryStateId: (state: EditorState) => string | undefined =
  pmh.getHistoryStateId;
/**
Whether the unique IDs of the history for the given editor state matches
the passed ID.
*/
const matchesTaggedHistory: (state: EditorState, id: string) => boolean =
  pmh.matchesTaggedHistory;

export {
  closeHistory,
  getHistoryStateId,
  history,
  isHistoryTransaction,
  matchesTaggedHistory,
  redo,
  redoDepth,
  redoNoScroll,
  undo,
  undoDepth,
  undoNoScroll,
};
