export { removeProperty } from './remove-property';
export { selectNodeByRdfaId } from './select-node-by-rdfa-id';
export { selectNodeByResource } from './select-node-by-resource';
export { addProperty } from './add-property';
export { removeBacklinkFromLiteral } from './remove-literal-backlink';
export { removeBacklinkFromResource } from './remove-resource-backlink';
export { insertRelation } from './insert-relation';
export { removeNodeWithChildNodes } from '@lblod/ember-rdfa-editor/commands/_private/rdfa-commands/remove-node-with-properties';
export { commandWrapper } from '@lblod/ember-rdfa-editor/commands/_private/rdfa-commands/remove-node-with-properties';
