const prefixableRdfaKeywords = [
  'typeof',
  'property',
  'src',
  'rel',
  'href',
  'resource',
  'about',
  'datatype',
];

const rdfaKeywords = prefixableRdfaKeywords.concat([
  'vocab',
  'prefix',
  'content',
]);

const defaultPrefixes = {
  as: 'https://www.w3.org/ns/activitystreams#',
  csvw: 'http://www.w3.org/ns/csvw#',
  dcat: 'http://www.w3.org/ns/dcat#',
  dqv: 'http://www.w3.org/ns/dqv#',
  duv: 'https://www.w3.org/TR/vocab-duv#',
  grddl: 'http://www.w3.org/2003/g/data-view#',
  ldp: 'http://www.w3.org/ns/ldp#',
  ma: 'http://www.w3.org/ns/ma-ont#',
  oa: 'http://www.w3.org/ns/oa#',
  org: 'http://www.w3.org/ns/org#',
  owl: 'http://www.w3.org/2002/07/owl#',
  prov: 'http://www.w3.org/ns/prov#',
  qb: 'http://purl.org/linked-data/cube#',
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  rdfa: 'http://www.w3.org/ns/rdfa#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  rif: 'http://www.w3.org/2007/rif#',
  rr: 'http://www.w3.org/ns/r2rml#',
  sd: 'http://www.w3.org/ns/sparql-service-description#',
  skos: 'http://www.w3.org/2004/02/skos/core#',
  skosxl: 'http://www.w3.org/2008/05/skos-xl#',
  ssn: 'http://www.w3.org/ns/ssn/',
  sosa: 'http://www.w3.org/ns/sosa/',
  time: 'http://www.w3.org/2006/time#',
  void: 'http://rdfs.org/ns/void#',
  wdr: 'http://www.w3.org/2007/05/powder#',
  wdrs: 'http://www.w3.org/2007/05/powder-s#',
  xhv: 'http://www.w3.org/1999/xhtml/vocab#',
  xml: 'http://www.w3.org/XML/1998/namespace',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
  cc: 'http://creativecommons.org/ns#',
  ctag: 'http://commontag.org/ns#',
  dc: 'http://purl.org/dc/terms/',
  dct: 'http://purl.org/dc/terms/',
  dcterms: 'http://purl.org/dc/terms/',
  dc11: 'http://purl.org/dc/elements/1.1/',
  foaf: 'http://xmlns.com/foaf/0.1/',
  gr: 'http://purl.org/goodrelations/v1#',
  ical: 'http://www.w3.org/2002/12/cal/icaltzd#',
  og: 'http://ogp.me/ns#',
  rev: 'http://purl.org/stuff/rev#',
  sioc: 'http://rdfs.org/sioc/ns#',
  v: 'http://rdf.data-vocabulary.org/#',
  vcard: 'http://www.w3.org/2006/vcard/ns#',
  schema: 'http://schema.org/',
  ext: 'http://mu.semte.ch/vocabularies/ext/',
  person: 'http://www.w3.org/ns/person#',
  eli: 'http://data.europa.eu/eli/ontology#',
  say: 'https://say.data.gift/ns/',
  dateplugin: 'http://say.data.gift/manipulators/insertion/',
  mandaat: 'http://data.vlaanderen.be/ns/mandaat#',
  besluit: 'http://data.vlaanderen.be/ns/besluit#',
  dossier: 'https://data.vlaanderen.be/ns/dossier',
  persoon: 'http://data.vlaanderen.be/ns/persoon#',
  besluittype: 'https://data.vlaanderen.be/id/concept/BesluitType/',
  besluitpublicatie:
    'https://data.vlaanderen.be/doc/applicatieprofiel/besluit-publicatie#',
  mobiliteit: 'https://data.vlaanderen.be/ns/mobiliteit#',
  lblodgn: 'http://data.lblod.info/vocabularies/gelinktnotuleren/',
  lblodmow: 'http://data.lblod.info/vocabularies/mobiliteit/',
};

export { rdfaKeywords, prefixableRdfaKeywords, defaultPrefixes };
