steps:
  changelog:
    image: danlynn/ember-cli:4.8.0
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep "\.changeset/.*\.md"
when:
  event:
    - pull_request
