steps:
  version:
    image: node:22-slim
    directory: packages/ember-rdfa-editor
    commands:
      - npm version --no-git-tag-version ${CI_COMMIT_TAG##@lblod/ember-rdfa-editor@}
  publish:
    image: node:22-slim
    commands:
      - npm config set ignore-scripts true
      - cat .npmrc
      # installing the latest corepack manually because of https://github.com/nodejs/corepack/issues/612
      - npm i -g corepack@0.31
      # pnpm doesn't handle this setting well, so we do it with npm
      - npm config set --location project '//registry.npmjs.org/:_authToken' "${NPM_ACCESS_TOKEN}"
      - pnpm i --frozen-lockfile
      - pnpm build
      - pnpm publish packages/ember-rdfa-editor --access public --tag dev --no-git-checks
    environment:
      NPM_ACCESS_TOKEN:
        from_secret: npm_access_token
when:
  event: tag
  ref: refs/tags/@lblod/ember-rdfa-editor@*-dev.*
