steps:
  e2e:
    # this image must be the same as in `scripts/e2e.sh`
    image: mcr.microsoft.com/playwright:v1.45.0-jammy
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
      - pnpm e2e:run
      # Ideally we would also run the visual regression tests, but we need to fix the update process
      # for them first
      # - pnpm playwright test
when:
  event:
    - pull_request
