steps:
  e2e:
    # this image must be the same as in `scripts/e2e.sh`
    image: mcr.microsoft.com/playwright:v1.41.2-jammy
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
      - pnpm playwright test
when:
  event:
    - pull_request
