matrix:
  scenario:
    - ember-lts-3.28
    # Disabled for now, we're running into server memory limitations which makes some jobs fail.
    # - embroider-safe
    # - embroider-optimized
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
      - npx ember try:one ${scenario}
when:
  event:
    - pull_request
