steps:
  push-latest:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  branch: master
  event: push
