steps:
  install:
    image: node:24-slim
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      - pnpm i --frozen-lockfile
  release-next:
    image: node:24-slim
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      # pnpm doesn't handle this setting well, so we do it with npm
      - npm config set --location project '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - pnpm --filter @lblod/ember-rdfa-editor build
      - pnpm --filter @lblod/say-roadsign-regulation-plugin build
      - pnpm publish packages/say-roadsign-regulation-plugin --access public --tag next --no-git-checks
    environment:
      NPM_TOKEN:
        from_secret: npm_access_token
    when:
      ref:
        include: refs/tags/@lblod/say-roadsign-regulation-plugin@*-next.*
  release:
    image: node:24-slim
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      # pnpm doesn't handle this setting well, so we do it with npm
      - npm config set --location project '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - pnpm --filter @lblod/ember-rdfa-editor build
      - pnpm --filter @lblod/say-roadsign-regulation-plugin build
      - pnpm publish packages/say-roadsign-regulation-plugin --access public --tag latest --no-git-checks
    environment:
      NPM_TOKEN:
        from_secret: npm_access_token
    when:
      ref:
        exclude: refs/tags/@lblod/say-roadsign-regulation-plugin@*-*
when:
  event: tag
  ref:
    include: refs/tags/@lblod/say-roadsign-regulation-plugin@*
    exclude: refs/tags/@lblod/say-roadsign-regulation-plugin@*-dev.*
