steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  release-next:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      tag: next
    when:
      ref:
        include: refs/tags/*-next.*
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
    when:
      ref:
        exclude: refs/tags/*-*
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  ref: refs/tags/v*
