steps:
  version:
    image: node:22-slim
    directory: packages/ember-rdfa-editor
    commands:
      - npm version --no-git-tag-version $(npm pkg get version | sed 's/"//g')-dev.${CI_COMMIT_SHA}
  publish:
    image: node:22-slim
    commands:
      - npm config set ignore-scripts true
      - cat .npmrc
      # installing the latest corepack manually because of https://github.com/nodejs/corepack/issues/612
      - npm i -g corepack@0.31
      - pnpm config --location project set '//registry.npmjs.org/:_authToken' $NPM_ACCESS_TOKEN
      - pnpm i --frozen-lockfile
      - pnpm build
      - pnpm publish packages/ember-rdfa-editor --access public --tag next --no-git-checks
    environment:
      NPM_ACCESS_TOKEN:
        from_secret: npm_access_token
when:
  - event: push
