steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  version:
    image: node:22-slim
    commands:
      - npm version --no-git-tag-version $(npm pkg get version | sed 's/"//g')-dev.${CI_COMMIT_SHA}
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      tag: dev
when:
  - event: push
