steps:
  test-compat:
    image: node:22-slim
    commands:
      # installing the latest corepack manually because of https://github.com/nodejs/corepack/issues/612
      - npm i -g corepack@0.31
      - pnpm i --no-frozen-lockfile
      - pnpm test:quickstart

when:
  event:
    - pull_request

depends_on:
  - verify-pr
