steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      - npm config set ignore-scripts true
      # pinning to 10.0.0 because of https://github.com/nodejs/corepack/issues/612
      # corepack use also runs an install
      - corepack use pnpm@10.0.0
      - pnpm build
  lint:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.1.0
    group: lint
    commands:
      - corepack enable
      - pnpm test
when:
  event:
    - pull_request
