steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint
  test:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - corepack enable
      - pnpm test:ember
  test-compat:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - corepack enable
      - pnpm test:ember-compatibility
  prepack:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm prepack
when:
  event:
    - pull_request
