steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  build:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm build
  lint:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.1.0
    commands:
      - corepack enable
      - pnpm test
  prepack:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm prepack
when:
  event:
    - pull_request
