steps:
  install:
    image: node:24-slim
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      - corepack enable
      - pnpm i --frozen-lockfile
      - pnpm build
      # resync injected addon build
      - pnpm i -f
  lint:
    image: node:24-slim
    depends_on: [install]
    commands:
      - npm i -g corepack@0.35
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.5.0
    depends_on: [install]
    commands:
      - npm i -g corepack@0.35
      - pnpm test
when:
  event:
    - pull_request
