steps:
  install:
    image: node:22-slim
    commands:
      - npm config set ignore-scripts true
      # pinning to 10.0.0 because of https://github.com/nodejs/corepack/issues/612
      # corepack use also runs an install
      # installing the latest corepack manually because of https://github.com/nodejs/corepack/issues/612
      - npm i -g corepack@0.31
      - corepack enable
      - pnpm i --frozen-lockfile
      - pnpm build
      # resync injected addon build
      - pnpm i -f
  lint:
    image: node:22-slim
    group: lint
    commands:
      - npm i -g corepack@0.31
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.1.0
    group: lint
    commands:
      - npm i -g corepack@0.31
      - pnpm test
when:
  event:
    - pull_request
