steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      # this will also build the addon by default
      - pnpm i --frozen-lockfile
  lint:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.1.0
    commands:
      - corepack enable
      - pnpm test
  prepack:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm prepack
when:
  event:
    - pull_request
