steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      # pinning to 10.0.0 because of https://github.com/nodejs/corepack/issues/612
      - corepack use pnpm@10.0.0
      # this will also build the addon by default
      - pnpm i --frozen-lockfile
  lint:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - corepack use pnpm@10.0.0
      - pnpm lint
  test:
    image: danlynn/ember-cli:6.1.0
    commands:
      - corepack enable
      - corepack use pnpm@10.0.0
      - pnpm test
  prepack:
    image: node:22-slim
    commands:
      - corepack enable
      - corepack use pnpm@10.0.0
      - pnpm prepack
when:
  event:
    - pull_request
